name: 'ECR Token Retrieval'
description: 'Exchange a Github Token for a scoped STS session token. Sets ENV variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, and ECR_HOSTNAME (registry uri)'
author: 'Blake Hyde <blake.hyde@inmar.com>'
inputs:
  github_token:
    description: 'Github action token'
    required: true
  ecr_token_vendor_url:
    description: 'URL of an instance of the ECR token vendor service'
    required: true
  github_repo:
    description: 'The name of the Github repo, in org/repo format'
    required: true
  subrepos:
    description: 'A comma-delimited list of subrepos to create/use in ECR'
    required: false
  include_root:
    description: 'Whether to create a repository with no subrepo name in ECR'
    required: false
runs:
  using: 'node12'
  main: 'target/main.js'
